<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>output_email</name>
   <tag></tag>
   <elementGuidId>665e1bfe-bf60-481c-8f60-464dd11ae3fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[@id='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[@id='email']</value>
      <webElementGuid>a720f83a-3d41-47a8-b90f-c6a464fa68e1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
