<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_buttons</name>
   <tag></tag>
   <elementGuidId>326325d0-b478-435e-8844-fd61f684f4e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Buttons']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Buttons']</value>
      <webElementGuid>27c34579-54e4-43ac-8308-342fea068054</webElementGuid>
   </webElementProperties>
</WebElementEntity>
